### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by WilliamOConnell** [TeensForTeens/platform#20]
The header and footer need a new look. I'm on it.

**Comment by WilliamOConnell** [comment]
Most of it is done, but it would be nice if on mobile it could expand/contract with a button, like in [this](http://purecss.io/layouts/tucked-menu-vertical) example. If someone knows a good way to do it, please do.

**Comment by an-empty-string** [comment]
Pure should be able to do this, feel free to reassign the issue to anyone who you feel can handle it

**Comment by Danimal15** [comment]
Yes can I also be assigned?

**Comment by WilliamOConnell** [comment]
Could you maybe do one of the pages that doesn't already have someone else assigned?
