### ISSUE TITLE
Pages - Our Platform

### ISSUE THREAD

**Issue by WilliamOConnell** [TeensForTeens/platform#35]
The "Our Platform" page. If you're interested, click "assign yourself" on the right and get started! If you can't assign yourself, for now just leave a comment.

![platform vision t4t](https://cloud.githubusercontent.com/assets/15237366/16805851/0d22eda4-48e0-11e6-8e6c-6a047f85021e.png)

**Comment by niharikavattikonda** [comment]
I can take this - for some reason it won't let me assign myself.

**Comment by Danimal15** [comment]
YEs can I also be assigned?

**Comment by evanyeyeye** [comment]
Can I be assigned? I see there are some assigned but I'm close to being finished.

**Comment by theycallmezeal** [comment]
Just a thought. About that title portion - no other pages use a similar style of header. For consistency's sake, should we choose one and stick with it?

![image](https://cloud.githubusercontent.com/assets/2685039/17073785/011fc46e-5042-11e6-9425-236181a51d44.png)

![image](https://cloud.githubusercontent.com/assets/2685039/17073800/0fa0376c-5042-11e6-896d-8ae50e98bae6.png)

![image](https://cloud.githubusercontent.com/assets/2685039/17073802/1a0d86fa-5042-11e6-87ec-dd7c4d624732.png)

Here be the three different title portions.

**Comment by niharikavattikonda** [comment]
I've actually decided to scale back my involvement for now, so if you could assign this to someone else that'd be great!

**Comment by theycallmezeal** [comment]
Ben says that the header for all three pages should now consistently use the rounded rectangle-style title like in picture 3 or the about-us page.

@evanyeyeye, ping.

The styles are already ready to be dropped into any page with ease: just set your extra_css to add multiple css files:

```
{% set extra_css = ["huge-header", "about"] %}
```

And then write your title like this:

```
<div id="huge-header">
    <h1>About Us</h1>
</div>
```
