### ISSUE TITLE
Pages - Login

### ISSUE THREAD

**Issue by WilliamOConnell** [TeensForTeens/platform#36]
The user login page. Look back at the old site so you know how to set up the form. If you're interested, click "assign yourself" on the right and get started! If you can't assign yourself, for now just leave a comment.

![login vision t4t](https://cloud.githubusercontent.com/assets/15237366/16805960/8ee35cac-48e0-11e6-928e-0d5d281222ac.png)

**Comment by an-empty-string** [comment]
this is not actually required if we are reusing the old set of volunteer pages
