### ISSUE TITLE
Pages - Sign Up

### ISSUE THREAD

**Issue by WilliamOConnell** [TeensForTeens/platform#37]
The "Get Involved" page. Look back at the old site so you know how to set up the form. If you're interested, click "assign yourself" on the right and get started! If you can't assign yourself, for now just leave a comment.

![joinus vision t4t](https://cloud.githubusercontent.com/assets/15237366/16806282/dfb5a116-48e1-11e6-852c-af808e5d8bf8.png)

**Comment by an-empty-string** [comment]
this is not actually required if we are reusing the old set of volunteer pages

**Comment by theycallmezeal** [comment]
So what is the ultimate fate of this page?

I've assigned myself and will take this on if needed.

**Comment by theycallmezeal** [comment]
Alright, the ball's in the backend court now.
