### ISSUE TITLE
set extra_css shenanigans

### ISSUE THREAD

**Issue by theycallmezeal** [TeensForTeens/platform#60]
Two things:

Currently, it'll look for the CSS in /static when it should look in /static/css.

Also, can it be made so that I can use multiple extra_css to add multiple external stylesheets?

**Comment by an-empty-string** [comment]
Are there any pages that depend on this functionality?

> Currently, it'll look for the CSS in /static when it should look in /static/css.

**Comment by ovkulkarni** [comment]
This was fixed in the recurring donations branch, I'll cherry pick the commit when I get home
